### PR TITLE
Optimize ui_cp_charts

### PR DESCRIPTION
**Pull request by tonyfujs**
This is a clean-up and small optimization of the `ui_cp_*` family of functions that support the country profile page. A few things were done:
- Remove `magrittr` dependencies and use the native pipe instead
- Remove unused code chunks. (Old code that was needed at some point, but no longer is)
- Minimize the number of calls to the `pip` function. (More optimization can be done, but it would imply a change of the endpoints,and ITS would have to make some UI code changes. Given the short timeline until the PIP update, this is not a good idea to make those changes now.

I have kept both the original, non-optimized functions, and the optimized ones to facilitate comparison and testing during the PR review. I'll remove the old functions once the PR is approved.

### CODE REVIEW

**Comment by shahronak47** [comment]
Hi @tonyfujs , 

I am testing this on `pip-fake-data` folder and I am getting an error in `ui_cp_charts_optim` function. 
```
devtools::load_all()

lkups <- create_versioned_lkups(data_dir = "../pip-fake-data/")
lkup <-  lkups$versions_paths$`20211212_2011_01_01_PROD`

ui_cp_charts(lkup = lkup)
ui_cp_charts_optim(lkup = lkup)
```

>Error in .prepareFastSubset(isub = isub, x = x, enclos = parent.frame(), :
RHS of == is length 0 which is not 1 or nrow (14). For robustness, no recycling is allowed (other than of length 1 RHS). Consider %in% instead.

When I change the data it works for `ui_cp_charts*` function but fails for `ui_cp_key_indicators*` functions

```
lkup <-  lkups$versions_paths$`20220810_2017_01_02_PROD`
ui_cp_key_indicators(lkup = lkup)
ui_cp_key_indicators_optim(lkup = lkup)
```

>Error in `[.data.table`(out, , .SD, .SDcols = lkup$pip_cols) :
Some items of .SDcols are not column names: [poverty_line]

I am not sure, if this is issue with the data or the code.

**Comment by tonyfujs** [comment]
Thanks @shahronak47 the `pip-fake-data` is probably outdated... This should be tested on a copy of the data available on the PIP drive. You know where to find it, right?

**Comment by shahronak47** [comment]
Can you help me set up the path for `data_dir` in `create_versioned_lkups` ? @tonyfujs

**Comment by tonyfujs** [comment]
Hey @shahronak47 I just sent it to you via Teams chat.

**Comment by shahronak47** [comment]
Hi @tonyfujs , 

I am still getting the same error for `ui_cp_key_indicators*` functions

```
lkup <-  lkups$versions_paths$`20230328_2017_01_02_PROD`
ui_cp_key_indicators(lkup = lkup)
ui_cp_key_indicators_optim(lkup = lkup)
```
>Error in `[.data.table`(out, , .SD, .SDcols = lkup$pip_cols) :
Some items of .SDcols are not column names: [poverty_line]

but since this error occurs for both `ui_cp_key_indicators` and `ui_cp_key_indicators_optim` functions it is not related to your change. Rest of the things look fine.

**Review by shahronak47 — APPROVED** [review]

**Pull request merged**
