### PR TITLE
Add reporting_level to ui_cp_poverty_charts()

### PR DESCRIPTION
**Pull request by Aeilert**
See #149

If we want reporting level to be part of the pop-up in the UI we will need to raise a separate issue on TFS, but adding it to the API endpoint is a prerequisite.

### CODE REVIEW

**Review by tonyfujs — COMMENTED** [review]
Thanks @Aeilert 
I have 4 failing unit tests, but 3 of them are because of the incorrect "national" level ARG survey. Even after doing a git pull from the TFS repo. This record is still here.

The other failing unit test is this one:
image
Any idea why it would fail?

**Comment by Aeilert** [comment]
Thanks Tony, 

Yes. ARG will be resolved in the coming pipeline run. 

As for the `ui_svy_metaI()` failing test: I believe that is because MHL has been added as a country to PIP, but is not yet part of the prod table that generates country query control values. This should also be fixed in the next pipeline run. Otherwise there is a discrepancy between CP and PC data that we should resolve, but not related to this PR.

**Comment by tonyfujs** [comment]
Got it. Thanks @Aeilert . So we are good with this one then? It can be merged, right?

**Comment by Aeilert** [comment]
Yep. This one should be good. Will merge.

**Pull request merged**
