### PR TITLE
Add test for median and SPL in fillgaps = TRUE

### PR DESCRIPTION
**Pull request by randrescastaneda**

### CODE REVIEW

**Comment by tonyfujs** [comment]
Thanks @randrescastaneda Do all tests pass for you? I have some failing...
image

**Comment by randrescastaneda** [comment]
That's very weird. All tests passed to me. I'll check.

R.Andrés Castañeda

Ps: I apologize for typos and brevity.
Sent from my iPhone
----------------------
Development Economics, Data Group
+1 (202) 473-0108 | Room MC 2-860
randrescastaneda.rbind.io
The World Bank Group

________________________________

**Comment by randrescastaneda** [comment]
Tony, did you check your cache? As far as I can see, you're getting no medians at all. Am I missing somethin?

R.Andrés Castañeda

Ps: I apologize for typos and brevity.
Sent from my iPhone
----------------------
Development Economics, Data Group
+1 (202) 473-0108 | Room MC 2-860
randrescastaneda.rbind.io
The World Bank Group

________________________________

**Comment by tonyfujs** [comment]
Duh! That was indeed the issue. I had not disabled the cache. Everything's good now. Merging.

**Pull request merged**
