### PR TITLE
Optimize pip grp logic

### PR DESCRIPTION
**Pull request by tonyfujs**
There are two functions in this branch to facilitate comparison and benchmarking. Once I get your feedback, I can clean-up and merge.

Below are a few tests I conducted to make sure the two functions returned the same results. PLease feel free to add to it.

`my_countries <- "WLD"
my_countries <- c("AFW", "AFE")
my_countries <- c("SSA", "LAC")
my_countries <- c("SSA", "LAC", "AFW")
my_countries <- c("ALL")

old <- pip_grp_logic_copy(country = my_countries,
year = "ALL",
povline = 6.85,
welfare_type = "all",
reporting_level = "all",
group_by = "wb",
lkup = lkup)

new <- pip_grp_logic2(country = my_countries,
year = "ALL",
povline = 6.85,
welfare_type = "all",
reporting_level = "all",
group_by = "wb",
lkup = lkup)

testthat::compare(old, new)`

### CODE REVIEW

**Review by randrescastaneda — APPROVED** [review]
Hi Tony, 

I tested the new logic at it seems to be working very, very well. Great. It is specially faster for queries with no-official regions (which is what we needed to improve). The queries with only official regions is improved as well but marginally. 

I think we are good to go. 


## At least one no-official region
image

## with only official regions
image

**Comment by randrescastaneda** [comment]
Hi @tonyfujs , 

In your examples, I did not find function `pip_grp_logic2` but `pip_grp_logic_copy` and `pip_grp_logic`, which I guess are old and new, respectively.

Best,

**Comment by tonyfujs** [comment]
> Hi @tonyfujs ,
> 
> In your examples, I did not find function `pip_grp_logic2` but `pip_grp_logic_copy` and `pip_grp_logic`, which I guess are old and new, respectively.
> 
> Best,

Thanks @randrescastaneda Indeed, `pip_grp_logic2` was from the old PR. I left it in the comment by mistake.

Great. I'll merge it. 

You're right, the main optimization happens when non-official regions are selected: This when duplicate computations used to happen. The rest is indeed fairly minor.

**Comment by tonyfujs** [comment]
Hi @randrescastaneda 

Before I merge this PR, can you check something for me, I get some (non systematic) unit tests errors. I think those error were due to the fact that both `pip_grp()` and `pip_grp_logic()` were both cached. Only `pip_grp_logic()` is now cached. But can you do the following, and let me know what happens:
- Pull the most recent branch of optimize_pip_grp_logic
- run `devtools::test()`
- run `devtools::check()`

Are you getting any error? Thanks!

**Comment by randrescastaneda** [comment]
Hi @tonyfujs , 

I did what you suggested and I also got some errors in `pip_grp_logic` tests (see below), plus some others in the plumber tests. As you said, I also think that the problems are related to the caching because I ran the tests manually and they worked fine. I can take a look at them again on Thursday. Does that work? 


image

**Comment by tonyfujs** [comment]
Thanks @randrescastaneda Yes, that works. These are the same errors I am getting as well. Caching of `pip_grp()` has been removed on this branch, so this error should no longer happen... That's why I am getting confused. It may need a full re-install of pipapi using this branch.

**Pull request merged**
