### PR TITLE
Improve cache for cp

### PR DESCRIPTION
**Pull request by shahronak47**
To improve caching make the `pip` call for all countries.

### CODE REVIEW

**Review by randrescastaneda — APPROVED** [review]
I agree with all changes

**Comment by randrescastaneda** [comment]
Hi @tonyfujs , 

This PR incorporates the changes that optimize the call in Country Profiles page. Running the pre cache with this should be extremely fast. I agreed with the changes, but please I would like to make sure you agree with the changes. 

Thanks.

**Review by tonyfujs — APPROVED** [review]
Looks good to me too.
- All tests passed
- Local Postman regression testing passed
- I removed caching to the `ui_cp_charts` and `ui_cp_key_indicators` functions as it is no longer needed
- I tested the new caching mechanism, and endpoints are returning really fast once they have been cached.

**Comment by randrescastaneda** [comment]
> Looks good to me too.
> 
> * All tests passed
> * Local Postman regression testing passed
> * I removed caching to the `ui_cp_charts` and `ui_cp_key_indicators` functions as it is no longer needed
> * I tested the new caching mechanism, and endpoints are returning really fast once they have been cached.

Fantastic. Thank you, Tony. I'll merge then.

**Pull request merged**
